# Generated by Django 2.2.1 on 2019-05-18 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_gloss', models.BooleanField(default=False)),
                ('enable_alternate_word', models.BooleanField(default=False)),
                ('enable_class', models.BooleanField(default=False)),
                ('enable_register', models.BooleanField(default=False)),
                ('enable_dialect', models.BooleanField(default=False)),
                ('enable_sampa', models.BooleanField(default=False)),
                ('enable_ipa', models.BooleanField(default=False)),
                ('enable_etymology', models.BooleanField(default=False)),
                ('enable_notes', models.BooleanField(default=False)),
                ('enable_sample', models.BooleanField(default=False)),
                ('enable_image_link', models.BooleanField(default=False)),
                ('allow_irregular_stems', models.CharField(choices=[('none', "Don't use these"), ('edit', 'Edit word page only'), ('both', 'Edit and Add word pages')], default='none', max_length=4)),
                ('is_private', models.BooleanField(choices=[(False, 'Public'), (True, 'Private')], default=False)),
                ('enable_roots', models.BooleanField(choices=[(False, "No, don't"), (True, 'Yes, allow it')], default=False)),
                ('clear_wordbank', models.CharField(choices=[('yes', 'Always'), ('no', 'Never'), ('ask', 'Ask each time')], default='yes', max_length=3)),
                ('display_field', models.CharField(choices=[('hint', 'Hint word'), ('note', 'Notes'), ('etym', 'Etymology'), ('lang', 'Source language'), ('none', 'None')], default='none', max_length=4)),
                ('classify_results', models.CharField(choices=[('pos', 'Only part of speech'), ('class', 'Only class'), ('both', 'Part of speech and class')], default='pos', max_length=5)),
                ('language', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='languages.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Wordlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.TextField()),
                ('alternative', models.TextField(blank=True)),
                ('gloss', models.TextField(blank=True)),
                ('pos', models.CharField(choices=[('', 'None'), ('abbr', 'Abbreviation'), ('adj', 'Adjective'), ('adp', 'Adposition'), ('adv', 'Adverb'), ('aff', 'Affix'), ('aux', 'Auxiliary'), ('conj', 'Conjunction'), ('det', 'Determiner'), ('intj', 'Interjection'), ('noun', 'Noun'), ('num', 'Numeral'), ('part', 'Particle'), ('phrs', 'Phrase'), ('prop', 'Proper noun'), ('pron', 'Pronoun'), ('verb', 'Verb')], default='', max_length=4)),
                ('dialects', models.TextField()),
                ('classes', models.TextField()),
                ('register', models.CharField(choices=[('wip', 'wip')], default='wip', max_length=3)),
                ('pronunciation_sampa', models.TextField()),
                ('pronunciation_ipa', models.TextField()),
                ('etymology', models.TextField()),
                ('notes', models.TextField()),
                ('sample', models.TextField()),
                ('image_link', models.URLField()),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Dictionary')),
                ('wordlink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.Wordlink')),
            ],
        ),
    ]
