# Generated by Django 2.2.1 on 2019-06-08 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlink',
            name='addedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.User'),
        ),
        migrations.AddField(
            model_name='wordlink',
            name='altname',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wordlink',
            name='hint',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='wordlink',
            name='islocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wordlink',
            name='linkname',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='wordlink',
            name='pos',
            field=models.CharField(choices=[('', 'None'), ('abbr', 'Abbreviation'), ('adj', 'Adjective'), ('adp', 'Adposition'), ('adv', 'Adverb'), ('aff', 'Affix'), ('aux', 'Auxiliary'), ('conj', 'Conjunction'), ('det', 'Determiner'), ('intj', 'Interjection'), ('noun', 'Noun'), ('num', 'Numeral'), ('part', 'Particle'), ('phrs', 'Phrase'), ('prop', 'Proper noun'), ('pron', 'Pronoun'), ('verb', 'Verb')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='display_field',
            field=models.CharField(choices=[('hint', 'Hint word'), ('note', 'Notes'), ('etym', 'Etymology'), ('none', 'None')], default='none', max_length=4),
        ),
    ]
